// Regenerate load-tools.ts by scanning content/tools/*.json
import * as fs from "fs";
import * as path from "path";

const TOOLS_DIR = path.join(process.cwd(), "content/tools");
const OUT_PATH = path.join(process.cwd(), "src/lib/load-tools.ts");

const files = fs.readdirSync(TOOLS_DIR).filter((f) => f.endsWith(".json")).sort();
const slugs = files.map((f) => f.replace(".json", ""));

const lines: string[] = [];
lines.push("// Dynamically import all tool JSON files using webpack context");
lines.push("// Auto-generated by scripts/generate-registry.ts — scan content/tools/");
lines.push("");
lines.push("const toolModules = {");
for (const slug of slugs) {
  lines.push(`  "${slug}": () => import("@/content/tools/${slug}.json"),`);
}
lines.push("};");
lines.push("");
lines.push('import type { Tool } from "./types";');
lines.push("");
lines.push("let _cache: Tool[] | null = null;");
lines.push("");
lines.push("export async function loadAllTools(): Promise<Tool[]> {");
lines.push("  if (_cache) return _cache;");
lines.push("  const results = await Promise.all(");
lines.push("    Object.values(toolModules).map((fn) => fn())");
lines.push("  );");
lines.push("  _cache = results");
lines.push('    .map((m) => (m as { default: Tool }).default ?? (m as Tool))');
lines.push('    .filter((t) => t.status === "published");');
lines.push("  return _cache;");
lines.push("}");

fs.writeFileSync(OUT_PATH, lines.join("\n") + "\n");
console.log(`Registry generated: ${slugs.length} tools`);
